### ISSUE TITLE
Confusing name

### ISSUE THREAD

**Issue by fearphage** [alexanderGugel/mockmock#1]
Nice library, but the name is confusing. This is actually a spy. Mocking libraries allow you to set expectations and confirm that they are met.

Your readme says _users_ shouldn't have to know the difference between spies, stubs, and mocks. I agree with that. Developers should though I believe.
- `spy` - watch things happen without interfering (transparent)
- `stub` - change/force behavior down specific paths
- `mock` - establish a list of expectations that should be met

In reality (in sinon), `mock` extends `stub` and `stub` extends `spy`.

**Comment by alexanderGugel** [comment]
Propose a better name if you want to. I think it's quite obvious that naming is not my strength.

**Comment by fearphage** [comment]
`spyspy` keeping with the same style of naming you have used.

Any reason to not try to make `sinon.spy` its own module instead of creating this one though? Sinon has great testing support already.

**Comment by alexanderGugel** [comment]
Send a PR if you feel strongly about that. I don't really care to be totally honest. This module is primarily meant for my own usage.
